### ISSUE TITLE
Homework week 3

### ISSUE THREAD

**Issue by kevinmccartney** [eewhy/js-app-dev-week3#1]
Hey Ey,

I took a look over your week 3 homework & had a couple callouts -

1. In `usingArrFunction.js`
    * Make sure that you're using the right amount of arguments in the `superHeroes.map` function call.
    * Uncomment the `console.log`ing of `secretIdentities` at the end of the program.
2. This totally isn't your fault, because the prompt was worded incorrectly, but in `particle.js`, uncomment line 16 so that the particle is moved.
3. Upload a screenshot of the completed Functional JS Nodeschool module.

**Comment by eewhy** [comment]
Completed :)

**Comment by kevinmccartney** [comment]
Thanks!
